### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by kFxDaKing** [renzuzu/renzu_scoreboard#1]
When you open scoreboard and close it by pressing "ESC" it gets duplicated for me.
![image](https://user-images.githubusercontent.com/52855882/127874878-418ab289-07e9-42ec-972d-15b9f50435c2.png)

**Comment by renzuzu** [comment]
thank you for mentioning this

https://github.com/renzuzu/renzu_scoreboard/commit/baf560278d5a35beba77d89d14cda23e3f2f48cb

**Comment by kFxDaKing** [comment]
Thank you for fix.
